services:
  frontend:
    container_name: frontend
    build:
      context: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
