apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        type: microservice
    spec:
      containers:
      - name: frontend-container
        image: palodaman/vikesplace-frontend:latest
        ports:
        - containerPort: 3000