volumes:
  psqldata:
    driver: local
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
  logstashdata:
    driver: local
  metricbeatdata:
    driver: local
  mongodbdata:
    driver: local
  neo4jdata:
    driver: local
  mongo_key:
    driver: local
  kafkadata:
    driver: local
  zookeeperdata:
    driver: local

networks:
  default:
    driver: bridge

services:
  # Referencing backend services
  postgresql:
    extends:
      file: backend/docker-compose.yml
      service: postgresql

  account:
    extends:
      file: backend/docker-compose.yml
      service: account

  ratings:
    extends:
      file: backend/docker-compose.yml
      service: ratings

  users:
    extends:
      file: backend/docker-compose.yml
      service: users

  messages:
    extends:
      file: backend/docker-compose.yml
      service: messages

  listing:
    extends:
      file: backend/docker-compose.yml
      service: listing

  charity:
    extends:
      file: backend/docker-compose.yml
      service: charity

  be-recommendation:
    extends:
      file: backend/docker-compose.yml
      service: recommendation

  be-search:
    extends:
      file: backend/docker-compose.yml
      service: be-search

  data_layer:
    extends:
      file: backend/docker-compose.yml
      service: data_layer
    depends_on:
      postgresql:
        condition: service_healthy

  postal_code_script:
    extends:
      file: backend/docker-compose.yml
      service: postal_code_script
    depends_on:
      - data_layer

  nginx:
    extends:
      file: backend/docker-compose.yml
      service: nginx
    depends_on:
      - be-search
      - be-recommendation
      - listing
      - messages
      - users
      - ratings
      - account
      - charity
  
  redis:
    extends:
      file: backend/docker-compose.yml
      service: redis


  # Referencing algorithm services
  setup:
    extends:
      file: algorithms/docker-compose.yml
      service: setup

  elasticsearch:
    extends:
      file: algorithms/docker-compose.yml
      service: elasticsearch
    depends_on:
      setup:
        condition: service_healthy

  kibana:
    extends:
      file: algorithms/docker-compose.yml
      service: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy

  metricbeat:
    extends:
      file: algorithms/docker-compose.yml
      service: metricbeat
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

  zookeeper:
    extends:
      file: algorithms/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: algorithms/docker-compose.yml
      service: kafka

  kafka-connect:
    extends:
      file: algorithms/docker-compose.yml
      service: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      neo4j:
        condition: service_healthy

  logstash:
    extends:
      file: algorithms/docker-compose.yml
      service: logstash
    depends_on:
      postgresql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      kafka:
        condition: service_healthy

  neo4j-relations-kafka-connect:
    extends:
      file: algorithms/docker-compose.yml
      service: neo4j-relations-kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      neo4j:
        condition: service_healthy

  neo4j:
    extends:
      file: algorithms/docker-compose.yml
      service: neo4j
    depends_on:
      kafka:
        condition: service_healthy

  mongodb:
    extends:
      file: algorithms/docker-compose.yml
      service: mongodb

  search:
    extends:
      file: algorithms/docker-compose.yml
      service: search
    depends_on:
      postgresql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  recommender:
    extends:
      file: algorithms/docker-compose.yml
      service: recommender
    depends_on:
      postgresql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      neo4j:
        condition: service_healthy


  # Referecing frontend
  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend