apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
        type: microservice
    spec:
      containers:
      - name: recommender-container
        image: palodaman/vikesplace-recommender:latest
        ports:
        - containerPort: 8001