version: "3"

services:
  account:
    container_name: account
    build:
      context: ./account
    volumes:
      - ./account:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
  users:
    container_name: users
    build:
      context: ./users
    volumes:
      - ./users:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
