version: "3"

services:
  authentication:
    container_name: authentication
    build:
      context: ./authentication
    volumes:
      - ./authentication:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
  ratings:
    container_name: ratings
    build:
      context: ./ratings
    volumes:
      - ./ratings:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
        
