version: "3"

services:
  authentication:
    container_name: authentication
    build:
      context: ./authentication
    volumes:
      - ./authentication:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
  ratings:
    container_name: ratings_reviews
    build:
      context: ./ratings_reviews
    volumes:
      - ./ratings_reviews:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
  users:
    container_name: users
    build:
      context: ./users
    volumes:
      - ./users:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
  listings:
    container_name: listings
    build:
      context: ./listings
    volumes:
      - ./listings:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
  recommendations:
    container_name: recommendations
    build:
      context: ./recommendations
    volumes:
      - ./recommendations:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
  searches:
    container_name: searches
    build:
      context: ./searches
    volumes:
      - ./searches:/app
    ports:
      - "5000"
    environment:
      PORT: 5000
