volumes:
  psqldata:
    driver: local

services:
  postgresql:
    image: postgis/postgis:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data_layer/data:/docker-entrypoint-initdb.d
      - psqldata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 45s
      timeout: 15s
      retries: 3
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
  
  account:
    container_name: account
    build:
      context: ./account
    volumes:
      - ./account:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5002:5000"
    environment:
      - DATA_LAYER=${DATA_LAYER}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - EMAIL=${EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
  
  ratings:
    container_name: ratings_reviews
    build:
      context: ./ratings_reviews
    volumes:
      - ./ratings_reviews:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5003:5000"
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DATA_LAYER=${DATA_LAYER}
  
  users:
    container_name: users
    build:
      context: ./users
    volumes:
      - ./users:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5004:5000"
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DATA_LAYER=${DATA_LAYER}
      - ALG_SEARCH=${ALG_SEARCH}
  
  messages:
    container_name: messages
    build:
      context: ./messages
    volumes:
      - ./messages:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5005:5000"
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DATA_LAYER=${DATA_LAYER}
  
  listing:
    container_name: listing
    build:
      context: ./listing
    volumes:
      - ./listing:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5010:5000"
    environment:
      - PORT=5000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DATA_LAYER=${DATA_LAYER}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  recommendation:
    container_name: recommendation
    build:
      context: ./recommendation
    volumes:
      - ./recommendation:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5006:5000"
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ALG_RECOMMENDATION=${ALG_RECOMMENDATION}
      - DATA_LAYER=${DATA_LAYER}
  
  be-search:
    container_name: be-search
    build:
      context: ./search
    volumes:
      - ./be-search:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5007:5000"
    environment:
      - ALG_SEARCH=${ALG_SEARCH}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DATA_LAYER=${DATA_LAYER}

  charity:
    container_name: charity
    build:
      context: ./charity
    volumes:
      - ./charity:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5008:5000"
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DATA_LAYER=${DATA_LAYER}
  
  data_layer:
    container_name: data_layer
    restart: on-failure
    build:
      context: ./data_layer
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./data_layer:/home/node/app
      - /home/node/app/node_module
    ports:
      - "3400:5000"
    environment:
      - PORT=5000
      - DATA_LAYER=${DATA_LAYER}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
  
  postal_code_script:
    container_name: postal_code_script
    build:
      context: ./data_layer
    volumes:
      - ./data_layer:/home/node/app
      - /home/node/app/node_module
    ports:
      - "5000"
    environment:
      - PORT=5000
      - DATA_LAYER=${DATA_LAYER}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    depends_on:
      postgresql:
        condition: service_healthy
    command: ["node", "populate_postal_codes.js"]
  
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    volumes:
      - ./nginx:/home/node/app
      - /home/node/app/node_module
    ports:
      - 8080:8080
