version: "3"

services:
  authentication:
    container_name: authentication
    build:
      context: ./authentication
    volumes:
      - ./authentication:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
