apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        type: microservice
    spec:
      containers:
      - name: frontend-container
        image: palodaman/vikesplace-mongodb:latest
        ports:
        - containerPort: 27017