apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
        type: microservice
    spec:
      containers:
      - name: search-container
        image: palodaman/vikesplace-search:latest
        ports:
        - containerPort: 5000