apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconnect-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafkaconnect
  template:
    metadata:
      labels:
        app: kafkaconnect
        type: microservice
    spec:
      containers:
      - name: kafkaconnect-container
        image: palodaman/vikesplace-kafkaconnect:latest
        ports:
        - containerPort: 8083