apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listing
  template:
    metadata:
      labels:
        app: listing
    spec:
      containers:
      - name: listing-container
        image: palodaman/vikesplace-listing:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000