apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: charity
  template:
    metadata:
      labels:
        app: charity
        type: microservice
    spec:
      containers:
      - name: charity-container
        image: palodaman/vikesplace-charity:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000