apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-layer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-layer
  template:
    metadata:
      labels:
        app: data_layer
        type: microservice
    spec:
      containers:
      - name: ratings-container
        image: palodaman/vikesplace-data_layer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000