apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
        type: microservice
    spec:
      containers:
      - name: recommendation-container
        image: palodaman/vikesplace-be-recommendation:latest
        ports:
        - containerPort: 5000